# Generated by Django 4.2.19 on 2025-02-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
