# Generated by Django 4.2.19 on 2025-02-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_delete_file_alter_encryptedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='key',
            field=models.FileField(blank=True, null=True, upload_to='keys/'),
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='file',
            field=models.FileField(upload_to='encrypted_files/'),
        ),
    ]
