# Generated by Django 4.2.19 on 2025-02-23 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_encryptedfile_key_alter_encryptedfile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='key',
        ),
    ]
