# Generated by Django 4.2.19 on 2025-02-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_encryptedfile_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
