# Generated by Django 4.2.19 on 2025-02-24 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_remove_encryptedfile_uploaded_at_encryptedfile_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 2, 24, 20, 49, 17, 876359, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encryptedfile',
            name='key',
            field=models.FileField(blank=True, null=True, upload_to='keys/'),
        ),
    ]
