# Generated by Django 4.2.19 on 2025-02-24 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_encryptedfile_is_encrypted_encryptedfile_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
